valid_categories = [
    "Art", "Science", "Information Technology", "Travel",
    "Philosophy", "operating systems", "chemistry", "javascript", 
    "Education & teaching", "Psychology", "Business",  
    "health & medical", "english", "communications",
    "nursing", "sociology", "excel", "arithmetic", "algebra", "biology", 
    "powerpoint", "cyber security","computer science", "cultural studies",
    "business law", "law", "literature", "programming", 
    "research & summaries", "physics", "other", "biochemistry", "pharmacy",
    "databases", "humanities","logo design", "web application", 
    "software engineering", "spanish", " macro economics", "economics", 
    "marketing", "civil engineering", "mechanical engineering",
    "mathematics", "accounting", "finance", "film", "statistics", 
    "email copy", "website design", "women studies", "networking", 
    "java","sports management", "dance", "music theory", "python", 
    "graphs", "html / css", "botany", "zoology", 
    "differential equations", "biomedical engineering", ".NET", 
    "internet research", "assembly language", "c programming", "c++",
    "c#" , "mysql", "social work", "calculus", "electrical engineering", 
    "data analytics", "political science", " earth and space exploration",
    "rocket science", "fitness", "discrete math", "geometry ", 
    "criminal justice", "geology", "geography", "business plans", 
    "american studies", "astrobiology", "international economies", 
    "game theory", "linguistics", "japanese", "php", "fashion design", "R",
    "population health", "genetics", "nutritional sciences", "policy", "probability",
    "applied mathematics", "algorithms & data structures", "web analytics",
    "agriculture", "cryptography", "data entry", "social justice", "entrepreneurship",
    "sales", "link building", "ecology", "linguistics", "cooking & baking",
    "music", "global studies", "jewish studies", "religion", "interior design", 
    "chiropractics", "hindi", "ethnic studies", "wellness", "macro economics", 
    "retail management", "growth theory", "international economics", "mathlab",
    "latin", "supply chain", "geographic information", "aerospace engineering", 
    "aeronautical management", "linux", "grammar", "scriptwriting", "hospitality",
    "application writing", "case studies", "marketing strategies"]   

